sudo: required
language: cpp
services:
  - docker
env:
  global:
    - secure: "gMIZ9+GDpaVmUi7CwSiwWPDBUfpcMfO4z5ABZtef1s9nSemjIQVdX2SZWyAyILZv7r37rvo5xPP/ZADjjME1hRBLrA5Q8qJz5nUieAkyJr7t0VNSH0znOxyK9v0XbPUAa/IcMCAbRrXnJ37hczZVbxvX5Y5xFFy10LXVV5E0nr8cQOqR5QLfrCLHRXPxO7jk1Jzr3r16BQ4L4PWB+KEVOukR9tCjWCzLivCrWt9hIbk59ChJR9d0eE02Kig9hWBW1fUylQ8jLF5nRi+3dFeBo0h7jDSP+2OiRpQRdbi2L6C8AV/mH1f/Oj7H+9JbA5qp0AGfh70nqro9ikKf+1DEA3Km6+ZKiR6Ak8FiL54FkyUhwTuyoRvi1uBl/gipcHq1clpkjXPYdS6CI9QbzKdxh1fwgIW62bF9ntb6igrObxpIVO7BfoUf5glJlqGyNj5teicvBTxRYvRv+hTWMNwFkWeRUp/xZ2XiaEd/TPVPxDJeiYvUJ+N54QUAhYTpFmUeDYg2pHDYVma5DMFk2TRHAHqcE88eilcOxtVHkrPyroVZ+jW1EN+cFGs/BMqJkrN4bt3SOcJv+n/RyfvGD0CBM4vj6JOZSvpA2bysPuyx+7DTwemOxAYXJLRgbOucPcqwmzRcvzxQa2H2Zql7gOlcBHwguVevX0bznpMldAK4Nyw=" # DOCKER_USER
    - secure: "b7bKT8JzBTiQzIYo05zffrOYjTQKIG4jC5G5HemCZxTSj1x5Sl6H1Z7LcxTyv/LwRcsvchppO8y3xoESr+PUkP9FbQoGf3gJ+x++h1EHEIouKM1JH/tMHPlT37B0CreIeUCPxVsXBTJDvkbnspJRm7WkwOOJLw9lohG6tpS9J37IdFqekM46VvKCpLJ2vPsTcsbXESpj17/xXGrN26RI3aB67GBxwl18lI+7kWezIj0u/sMUGRzmIVNNoGnKtV7m2Xro2/Dh9diNNGZgYPnG+a4hi3Z+Y/hM5b1utMOCF1dj43b+ESP2S1uyJkt4jN5tV6HU03vDgl29jSC+rThUqYOtuflFeLJtdMskVy6qjx7OWTKm1C+WApj7PxpYAOj1xLlpJGxDlViAuWWEJqVQW5BRE17mXf0Xq4qeFBDbIiIoAzbIxN1cSVqOwnh8PY/an1qpcpfXZIBn3blO2M7gvh4UIKEUSVLLEArfODWbJu7TF8FnapSNv/l+TQl0qepUzLZPzmGG5QvDGlm4sZ90BApJRud0k5icGVt5q/IRHo3h3tuSS2bRwnWod0WPcO8BWDQxOQZc+2qDhWwqFBpllXxpZaUhPocl/vgRDSr3RwVwlnlCVwcEUquhjszqra7lI4gBxeC6K6L4oMVXD42FgrUuOdXbjoTDANBeDX1Ekgk=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
before_install:
  - mkdir $(pwd)/build
  - docker pull spielhuus/buildimage:latest
  - sudo docker run -itd --name build -v $(pwd)/www:/repo -v $(pwd)/build:/build spielhuus/buildimage
  - sudo docker exec build apt-get -y update
  - sudo docker exec build apt-get -y install libsdl2-dev libboost-all-dev libao-dev libimlib2-dev libsqlite3-dev libxml++-dev libpcre++-dev libxml2-dev libmp3lame-dev libflac++-dev libpoppler-cpp-dev libcurl4-openssl-dev libcurlpp-dev libzmq-dev libsigc++-2.0-dev libssl-dev libarchive-dev uuid-dev libhiredis-dev libev-dev libmagic-dev libopencv-dev libmusicbrainz5-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavresample-dev libavcodec-extra
  - sudo docker exec build git clone https://github.com/squawkcpp/www.git /repo
script:
  - sudo docker exec build cmake -H/repo -B/build
  - sudo docker exec build cmake --build /build
  - sudo docker exec build cmake --build /build --target package

deploy:
  provider: releases
  api_key:
    secure: "PkcR+VgR0PzvGC+hc3SJPvUPjpV1juZAzMYOGi+Ez9Rgwuf06a5RAOHPnWwJ230ocEqGV6HQW/scufSZpahTpvB4e28nzoJSBcdmjWhNmy3NzENeseu6NgzhwJXtkfFYhMpoBTtT0E295CIvjY7PwvWG3oxhuzIfmMBHobKkGjJc8rQfGqhlzrYpja59luX4CqKVFasBRRGyeMaQ/zM6Ng9AKz23XwBUF7esyqwjPxbqFwrAgnn1ZL/PosCb2yb8GVuRl5/J0mSfLUxAeJ+T5z9Z4FLyeSWdzrKvNwFiOrPUAR/rC0hFqgYJOO7Bgf6wmF9uCLv6pfc/l/l9Y3FgERfDn8P3ijoixv9cQm8LkL2H1ysf0e+l/d0MlahZ2YMr5rZWKk29jZdBto7ceA0USXh4Ql+lsJHci4Yt9wm5RAZXn1fJKRMeahKIxwCuAIpDMGeTWnSmc42Y3meoAtIZNi8O481FGSo6n6xSOccMxqhnjZE+NGjvPOFSBZgy4Da0WnHZoSALFfDQGvExVEVPYTurltTlLNUUsPQk1W6qFPEMpDNZ0x77lIx0uhEWgj8gaIlHt00KhEAyUIWOAQm9WIqipyy/MmXN9SwdaQdwIxWBadGh4hft1zx6cBoyuBv51Bz5bdbldoKicrExMYqWmGveJdCzTFDCqmg3gC+HpEs="
  file: '$(pwd)/build/www_.deb'
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: squawkcpp/www

after_success:
  - sudo docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=squawk/www
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - sudo docker build -f Dockerfile -t $REPO:$COMMIT .
  - sudo docker tag $REPO:$COMMIT $REPO:$TAG
  - sudo docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - sudo docker push $REPO

